import os
import re
import json
import html
from urllib.parse import quote

SITE_URL = os.environ.get("SITE_URL", "").rstrip("/")
CHANNEL_URL = "https://t.me/e11lab_marketnews"


def esc(s):
    return html.escape(str(s), quote=True)


def slugify(text):
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:70].strip("-") or "story"


def bi(en, km, tag="span", cls=""):
    en = str(en)
    km = str(km).strip() if km else en
    extra = (" " + cls) if cls else ""
    return (
        f'<{tag} class="en{extra}" lang="en">{esc(en)}</{tag}>'
        f'<{tag} class="km{extra}" lang="km">{esc(km)}</{tag}>'
    )


UI = {
    "nav_news": ("News", "ព័ត៌មាន"),
    "nav_about": ("About", "អំពីយើង"),
    "nav_disclaimer": ("Disclaimer", "ការបដិសេធទំនួលខុសត្រូវ"),
    "join": ("Join Telegram for Daily Alert", "ចូលរួម Telegram សម្រាប់សារជូនដំណឹងប្រចាំថ្ងៃ"),
    "all_news": ("← All news", "← ព័ត៌មានទាំងអស់"),
    "takeaways": ("Key takeaways", "ចំណុចសំខាន់ៗ"),
    "source": ("Source", "ប្រភព"),
    "impact": ("XAU/USD impact", "ផលប៉ះពាល់លើ XAU/USD"),
    "share": ("Share", "ចែករំលែក"),
    "all": ("All", "ទាំងអស់"),
    "footer": (
        "© E11 Lab · Educational content only. Not financial advice.",
        "© E11 Lab · មាតិកាអប់រំប៉ុណ្ណោះ មិនមែនជាដំបូន្មានហិរញ្ញវត្ថុទេ។",
    ),
    "hero_title": ("Gold & Global Economy News", "ព័ត៌មានមាស និងសេដ្ឋកិច្ចពិភពលោក"),
    "hero_sub": (
        "Daily news that moves gold (XAU/USD), explained simply in English and Khmer.",
        "ព័ត៌មានប្រចាំថ្ងៃដែលជះឥទ្ធិពលដល់តម្លៃមាស (XAU/USD) ពន្យល់ងាយៗជាភាសាអង់គ្លេស និងខ្មែរ។",
    ),
    "no_results": ("No matching stories.", "រកមិនឃើញព័ត៌មានដែលត្រូវគ្នាទេ។"),
}

IMPACT_LABELS = {
    "bullish": ("▲ Bullish", "▲ ឡើង"),
    "bearish": ("▼ Bearish", "▼ ធ្លាក់"),
    "mixed": ("◆ Mixed", "◆ ចម្រុះ"),
    "neutral": ("● Neutral", "● អព្យាក្រឹត"),
}

ABOUT_EN = [
    "E11 Lab × THE MARKET CODE publishes daily market news and educational insight for gold (XAU/USD) traders.",
    "Our stories are written with the help of AI, based on public news sources, and every story links to its source. We explain what happened and why it may matter for gold.",
    "We do not give buy or sell signals, entries, stops or price targets.",
    "Every story is available in English and Khmer. Use the EN | ខ្មែរ switch at the top of the page.",
]
ABOUT_KM = [
    "E11 Lab × THE MARKET CODE ផ្សព្វផ្សាយព័ត៌មានទីផ្សារប្រចាំថ្ងៃ និងមាតិកាអប់រំសម្រាប់អ្នកជួញដូរមាស (XAU/USD)។",
    "អត្ថបទរបស់យើងត្រូវបានសរសេរដោយមានជំនួយពី AI ផ្អែកលើប្រភពព័ត៌មានសាធារណៈ ហើយអត្ថបទនីមួយៗមានតំណភ្ជាប់ទៅប្រភពដើម។ យើងពន្យល់ពីអ្វីដែលបានកើតឡើង និងមូលហេតុដែលវាអាចសំខាន់សម្រាប់មាស។",
    "យើងមិនផ្តល់សញ្ញាទិញ ឬលក់ ចំណុចចូល ចំណុចកាត់ខាត ឬគោលដៅតម្លៃឡើយ។",
    "អត្ថបទទាំងអស់មានជាភាសាអង់គ្លេស និងខ្មែរ។ សូមប្រើប៊ូតុង EN | ខ្មែរ នៅផ្នែកខាងលើនៃទំព័រ។",
]
DISCLAIMER_EN = [
    "All content on this website is for education and information only. It is not financial, investment or trading advice.",
    "Trading gold, Forex and other markets involves a high risk of loss. Past performance does not guarantee future results.",
    "Content is partly generated by AI and may contain errors or be out of date. Always check the source link and do your own research. Consider speaking with a licensed professional before making decisions.",
]
DISCLAIMER_KM = [
    "មាតិកាទាំងអស់នៅលើគេហទំព័រនេះគឺសម្រាប់ការអប់រំ និងផ្តល់ព័ត៌មានប៉ុណ្ណោះ។ វាមិនមែនជាដំបូន្មានហិរញ្ញវត្ថុ ការវិនិយោគ ឬការជួញដូរទេ។",
    "ការជួញដូរមាស Forex និងទីផ្សារផ្សេងទៀតមានហានិភ័យខ្ពស់នៃការបាត់បង់។ លទ្ធផលពីអតីតកាលមិនធានាលទ្ធផលនាពេលអនាគតទេ។",
    "មាតិកាខ្លះត្រូវបានបង្កើតដោយ AI ហើយអាចមានកំហុស ឬហួសសម័យ។ សូមពិនិត្យតំណភ្ជាប់ប្រភពជានិច្ច និងស្រាវជ្រាវដោយខ្លួនឯង។ សូមពិចារណាពិភាក្សាជាមួយអ្នកជំនាញដែលមានអាជ្ញាបណ្ណមុនធ្វើការសម្រេចចិត្ត។",
]

CSS = """
:root{--bg:#0a0e13;--card:#111821;--line:#1c2733;--text:#e6edf3;--muted:#8b98a5;--cyan:#22d3ee;--green:#34d399}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;line-height:1.7}
a{color:var(--cyan);text-decoration:none}
a:hover{text-decoration:underline}
html[data-lang="en"] .km{display:none}
html[data-lang="km"] .en{display:none}
.km{font-family:"Noto Sans Khmer",system-ui,sans-serif}
p.km,li.km{line-height:1.95}
header{padding:12px 20px;border-bottom:1px solid var(--line)}
.top{display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
.brand{font-weight:800;letter-spacing:.12em;font-size:14px;color:var(--text)}
.brand span{color:var(--green)}
nav{display:flex;gap:16px;font-size:14px;flex-wrap:wrap}
nav a{color:var(--text)}
.right{display:flex;align-items:center;gap:10px}
.join{background:var(--green);color:#052e1f;padding:5px 12px;border-radius:8px;font-size:14px;font-weight:600}
.join:hover{text-decoration:none;opacity:.9}
.lang button{background:transparent;color:var(--text);border:1px solid var(--line);padding:5px 12px;border-radius:8px;cursor:pointer;font-size:14px;font-family:inherit}
html[data-lang="en"] .b-en,html[data-lang="km"] .b-km{background:var(--cyan);color:#06222a;border-color:var(--cyan)}
main{max-width:920px;margin:0 auto;padding:26px 18px 60px}
h1{font-size:30px;line-height:1.3;margin:8px 0 18px}
.hero{padding:6px 0}
.btn{display:inline-block;background:var(--cyan);color:#06222a;padding:9px 18px;border-radius:10px;font-weight:700}
.btn:hover{text-decoration:none;opacity:.9}
.tools{display:flex;flex-wrap:wrap;gap:10px;align-items:center;margin:20px 0}
.tools input{flex:1 1 220px;background:var(--card);color:var(--text);border:1px solid var(--line);border-radius:10px;padding:9px 12px;font-size:15px;font-family:inherit}
.chip{background:transparent;color:var(--text);border:1px solid var(--line);padding:6px 14px;border-radius:999px;cursor:pointer;font-size:14px;font-family:inherit}
.chip.on{background:var(--cyan);color:#06222a;border-color:var(--cyan)}
.meta{color:var(--muted);font-size:14px;margin:0}
.badge{display:inline-block;background:var(--card);border:1px solid var(--green);color:var(--green);padding:3px 12px;border-radius:999px;font-size:14px;margin:6px 0 12px}
.mini{color:var(--green);font-size:12px;margin-left:8px}
.cover{width:100%;border-radius:12px;border:1px solid var(--line);margin:8px 0 20px}
.lead{font-size:19px;color:#cfe9ee;border-left:3px solid var(--green);padding-left:14px}
.box{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:6px 20px 10px;margin:26px 0}
.box h3{color:var(--green);margin:14px 0 6px}
.note{color:var(--muted);font-size:13px}
.share{color:var(--muted);font-size:14px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:18px}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;overflow:hidden;color:var(--text)}
.card:hover{border-color:var(--cyan);text-decoration:none}
.card img{width:100%;display:block;aspect-ratio:16/10;object-fit:cover}
.card .txt{padding:12px 14px 16px}
.card h2{font-size:17px;line-height:1.35;margin:6px 0}
.card p{margin:0;color:var(--muted);font-size:14px}
footer{text-align:center;color:var(--muted);font-size:13px;padding:30px 18px}
footer a{margin:0 8px}
.brand{display:inline-flex;align-items:center;gap:8px}
.logo{height:34px;width:auto}
"""

LANG_JS = """
(function(){
  var l='en';
  try{
    var p=new URLSearchParams(location.search).get('lang');
    var s=localStorage.getItem('lang');
    var n=(navigator.language||'').toLowerCase().indexOf('km')===0?'km':'en';
    l=p||s||n;
  }catch(e){}
  if(l!=='km'){l='en';}
  document.documentElement.setAttribute('data-lang',l);
  try{localStorage.setItem('lang',l);}catch(e){}
})();
function setLang(l){
  document.documentElement.setAttribute('data-lang',l);
  try{localStorage.setItem('lang',l);}catch(e){}
}
"""

FILTER_JS = """
var imp='all';
function applyFilter(){
  var q=(document.getElementById('q').value||'').toLowerCase().trim();
  var shown=0;
  document.querySelectorAll('#grid .card').forEach(function(c){
    var okQ=!q||c.getAttribute('data-text').indexOf(q)>-1;
    var okI=imp==='all'||c.getAttribute('data-impact')===imp;
    var ok=okQ&&okI;
    c.style.display=ok?'':'none';
    if(ok){shown++;}
  });
  var n=document.getElementById('none');
  if(n){n.style.display=shown?'none':'block';}
}
function setImp(v,btn){
  imp=v;
  document.querySelectorAll('.chip').forEach(function(b){b.classList.remove('on');});
  btn.classList.add('on');
  applyFilter();
}
"""


def header(root):
    nav = (
        "<nav>"
        f'<a href="{root}index.html">{bi(*UI["nav_news"])}</a>'
        f'<a href="{root}about.html">{bi(*UI["nav_about"])}</a>'
        f'<a href="{root}disclaimer.html">{bi(*UI["nav_disclaimer"])}</a>'
        "</nav>"
    )
    return (
        '<header><div class="top">'
        f'<a class="brand" href="{root}index.html">E11 LAB <span>× THE MARKET CODE</span></a>'
        f"{nav}"
        '<div class="right">'
        f'<a class="jo
        f'<a class="brand" href="{root}index.html"><img class="logo" src="{root}logo.png" alt="E11 Lab"> E11 LAB <span>× THE MARKET CODE</span></a>'
        '<div class="lang"><button class="b-en" onclick="setLang(\'en\')">EN</button>'
        '<button class="b-km" onclick="setLang(\'km\')">ខ្មែរ</button></div>'
        "</div></div></header>"
    )


def footer(root):
    return (
        "<footer>"
        f'<p><a href="{root}about.html">{bi(*UI["nav_about"])}</a>'
        f'<a href="{root}disclaimer.html">{bi(*UI["nav_disclaimer"])}</a>'
        f'<a href="{CHANNEL_URL}" target="_blank" rel="noopener">Telegram</a></p>'
        f'<p>{bi(*UI["footer"])}</p>'
        "</footer>"
    )


def page(title, body, root, desc="", image="", scripts=""):
    og = ""
    if image:
        og = (
            f'<meta property="og:image" content="{esc(image)}">'
            '<meta name="twitter:card" content="summary_large_image">'
        )
    return (
        '<!doctype html><html lang="en" data-lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        f'<link rel="icon" type="image/png" href="{root}favicon.png">'
        f'<meta name="description" content="{esc(desc)}">'
        f'<meta property="og:title" content="{esc(title)}">'
        f'<meta property="og:description" content="{esc(desc)}">'
        f"{og}"
        '<link rel="preconnect" href="https://fonts.googleapis.com">'
        '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
        '<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+Khmer:wght@400;600;700&display=swap" rel="stylesheet">'
        f"<script>{LANG_JS}</script>"
        f"<style>{CSS}</style></head><body>"
        f"{header(root)}"
        f"<main>{body}</main>"
        f"{footer(root)}"
        f"<script>{scripts}</script>"
        "</body></html>"
    )


def render_article(a, p_en, t_en, p_km, t_km):
    paras = "".join(
        bi(p, p_km[i] if i < len(p_km) else p, "p") for i, p in enumerate(p_en)
    )
    lis = "".join(
        bi(t, t_km[i] if i < len(t_km) else t, "li") for i, t in enumerate(t_en)
    )
    impact_en, impact_km = IMPACT_LABELS.get(a.get("impact", ""), ("", ""))
    badge = ""
    if impact_en:
        badge = (
            '<p><span class="badge">'
            + bi(f"{UI['impact'][0]}: {impact_en}", f"{UI['impact'][1]}: {impact_km}")
            + "</span></p>"
        )
    src = (
        f'<a href="{esc(a["source_url"])}" rel="noopener" target="_blank">'
        f'{esc(a["source_name"])}</a>'
    )
    note = bi(
        f"Original commentary by THE MARKET CODE, based on public reporting from "
        f"{a['source_name']}. Written with the help of AI. Educational only, not "
        f"financial advice.",
        f"មតិវិភាគដើមដោយ THE MARKET CODE ផ្អែកលើការរាយការណ៍សាធារណៈពី "
        f"{a['source_name']}។ សរសេរដោយមានជំនួយពី AI។ មាតិកាអប់រំប៉ុណ្ណោះ "
        f"មិនមែនជាដំបូន្មានហិរញ្ញវត្ថុទេ។",
        "p",
        "note",
    )
    share = ""
    if SITE_URL:
        page_url = f'{SITE_URL}/news/{a["slug"]}.html'
        tg = (
            "https://t.me/share/url?url=" + quote(page_url, safe="")
            + "&text=" + quote(a["headline"])
        )
        fb = "https://www.facebook.com/sharer/sharer.php?u=" + quote(page_url, safe="")
        share = (
            f'<p class="share">{bi(*UI["share"])}: '
            f'<a href="{esc(tg)}" target="_blank" rel="noopener">Telegram</a> · '
            f'<a href="{esc(fb)}" target="_blank" rel="noopener">Facebook</a></p>'
        )
    body = (
        "<article>"
        f'<p class="meta">{esc(a["date"])} · {bi(*UI["source"])}: {src}</p>'
        f'<h1>{bi(a["headline"], a.get("headline_km", ""))}</h1>'
        f"{badge}"
        f'<img class="cover" src="{esc(a["slug"])}.jpg" alt="">'
        f'{bi(a["teaser"], a.get("teaser_km", ""), "p", "lead")}'
        f"{paras}"
        f'<div class="box"><h3>{bi(*UI["takeaways"])}</h3><ul>{lis}</ul></div>'
        f"{share}"
        f"{note}"
        f'<p><a href="../index.html">{bi(*UI["all_news"])}</a></p>'
        "</article>"
    )
    image = f'{SITE_URL}/news/{a["slug"]}.jpg' if SITE_URL else ""
    return page(a["headline"] + " | E11 Lab", body, "../", a["teaser"], image)


def card_text(a):
    parts = [
        a.get("headline", ""),
        a.get("teaser", ""),
        a.get("headline_km", ""),
        a.get("teaser_km", ""),
    ]
    return " ".join(parts).lower()


def render_index(articles):
    chips = (
        f'<button class="chip on" onclick="setImp(\'all\',this)">{bi(*UI["all"])}</button>'
    )
    for key in ("bullish", "bearish", "mixed"):
        en, km = IMPACT_LABELS[key]
        chips += f'<button class="chip" onclick="setImp(\'{key}\',this)">{bi(en, km)}</button>'

    cards = ""
    for a in articles[:100]:
        en, km = IMPACT_LABELS.get(a.get("impact", ""), ("", ""))
        mini = f'<span class="mini">{bi(en, km)}</span>' if en else ""
        cards += (
            f'<a class="card" href="news/{esc(a["slug"])}.html" '
            f'data-impact="{esc(a.get("impact", ""))}" data-text="{esc(card_text(a))}">'
            f'<img src="news/{esc(a["slug"])}.jpg" alt="" loading="lazy">'
            f'<div class="txt"><span class="meta">{esc(a["date"])}</span>{mini}'
            f'<h2>{bi(a["headline"], a.get("headline_km", ""))}</h2>'
            f'{bi(a["teaser"], a.get("teaser_km", ""), "p")}</div></a>'
        )
    body = (
        '<section class="hero">'
        f'<h1>{bi(*UI["hero_title"])}</h1>'
        f'{bi(*UI["hero_sub"], "p", "lead")}'
        f'<p><a class="btn" href="{CHANNEL_URL}" target="_blank" rel="noopener">{bi(*UI["join"])}</a></p>'
        "</section>"
        '<div class="tools">'
        '<input id="q" type="search" placeholder="Search · ស្វែងរក" oninput="applyFilter()">'
        f"{chips}</div>"
        f'<div class="grid" id="grid">{cards}</div>'
        f'<p class="note" id="none" style="display:none">{bi(*UI["no_results"])}</p>'
    )
    return page(
        "Gold & Global Economy News | E11 Lab × THE MARKET CODE",
        body,
        "",
        "Daily news that moves gold (XAU/USD), in English and Khmer.",
        "",
        FILTER_JS,
    )


def render_text_page(title_key, paras_en, paras_km):
    paras = "".join(
        bi(p, paras_km[i] if i < len(paras_km) else p, "p") for i, p in enumerate(paras_en)
    )
    body = f'<h1>{bi(*UI[title_key])}</h1>{paras}'
    return page(UI[title_key][0] + " | E11 Lab", body, "", paras_en[0])


def render_sitemap(articles):
    items = [
        (SITE_URL + "/", ""),
        (SITE_URL + "/about.html", ""),
        (SITE_URL + "/disclaimer.html", ""),
    ]
    for a in articles:
        items.append((f'{SITE_URL}/news/{a["slug"]}.html', a["date"]))
    rows = ""
    for u, d in items:
        rows += f"<url><loc>{esc(u)}</loc>"
        if d:
            rows += f"<lastmod>{esc(d)}</lastmod>"
        rows += "</url>"
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
        + rows
        + "</urlset>"
    )


def load_articles(docs):
    try:
        with open(os.path.join(docs, "articles.json"), encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return []


def save_articles(docs, articles):
    with open(os.path.join(docs, "articles.json"), "w", encoding="utf-8") as f:
        json.dump(articles[:200], f, ensure_ascii=False, indent=2)


def write_static(docs, articles):
    os.makedirs(docs, exist_ok=True)
    with open(os.path.join(docs, "index.html"), "w", encoding="utf-8") as f:
        f.write(render_index(articles))
    with open(os.path.join(docs, "about.html"), "w", encoding="utf-8") as f:
        f.write(render_text_page("nav_about", ABOUT_EN, ABOUT_KM))
    with open(os.path.join(docs, "disclaimer.html"), "w", encoding="utf-8") as f:
        f.write(render_text_page("nav_disclaimer", DISCLAIMER_EN, DISCLAIMER_KM))
    if SITE_URL:
        with open(os.path.join(docs, "sitemap.xml"), "w", encoding="utf-8") as f:
            f.write(render_sitemap(articles))
        with open(os.path.join(docs, "robots.txt"), "w", encoding="utf-8") as f:
            f.write(f"User-agent: *\nAllow: /\nSitemap: {SITE_URL}/sitemap.xml\n")
    open(os.path.join(docs, ".nojekyll"), "a").close()


def write_site(docs, a, p_en, t_en, p_km, t_km, articles):
    os.makedirs(os.path.join(docs, "news"), exist_ok=True)
    with open(os.path.join(docs, "news", a["slug"] + ".html"), "w", encoding="utf-8") as f:
        f.write(render_article(a, p_en, t_en, p_km, t_km))
    write_static(docs, articles)
